name: Test package

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js 17.x
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 17.x

            - name: Install dependencies
              run: npm ci || npm install

            - name: Build project
              run: npm run build

            - name: Run tests
              run: npm test
